#!/bin/bash

aws ec2 run-instances --image-id ami-0a86f18b52e547759 --count 1 \
--instance-type t2.micro --key-name four --security-group-ids sg-0d10eed206355c736 \
--subnet-id subnet-f736998b --block-device-mapping file://mapping.json > create_file

cat create_file | jq '.Instances[].InstanceId' > ins_crd



#.Reservations[].Instances[].PublicDnsName, '
  
