#!/bin/bash

name=`cat /home/ubuntu/ec2/dns_inst | tr -d '"'`
> /home/ubuntu/.ssh/known_hosts

ssh-keyscan -H $name  >> /home/ubuntu/.ssh/known_hosts  

ssh-keyscan -H github.com >> /home/ubuntu/.ssh/known_hosts
